"""Generate src/survey/countries.py — the country list used by the survey.

The list is the intersection of ISO 3166-1 (pycountry) with the countries drawn
in data/world_countries.geojson, so every country offered by the form can also
be shaded on the map. Long ISO names are shortened for display.

Run AFTER scripts/build_geojson.py:
    uv run --with pycountry python scripts/gen_countries.py
"""

from __future__ import annotations

import json
from pathlib import Path

import pycountry

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "survey" / "countries.py"
GEOJSON = ROOT / "data" / "world_countries.geojson"

HEADER = '''"""Countries offered by the survey form (matched 1:1 to the map geometry).

Generated by scripts/gen_countries.py — ISO 3166-1 (pycountry) intersected with
data/world_countries.geojson, plus Kosovo (user-assigned XK). Do not edit by hand.
"""

from __future__ import annotations

Country = tuple[str, str]
'''

FOOTER = """
COUNTRY_BY_CODE: dict[str, str] = dict(COUNTRIES)
"""

# Friendlier than the long ISO full names.
DISPLAY_OVERRIDES = {
    "BA": "Bosnia and Herzegovina",  # no change, kept for completeness
    "BO": "Bolivia",
    "BN": "Brunei",
    "CD": "DR Congo",
    "CF": "Central African Republic",
    "CI": "Côte d'Ivoire",
    "CN": "China",
    "KP": "North Korea",
    "KR": "South Korea",
    "FM": "Micronesia",
    "GB": "United Kingdom",
    "IR": "Iran",
    "KG": "Kyrgyzstan",
    "LA": "Laos",
    "LK": "Sri Lanka",
    "MD": "Moldova",
    "MK": "North Macedonia",
    "MM": "Myanmar",
    "NE": "Niger",
    "NL": "Netherlands",
    "PS": "Palestine",
    "RU": "Russia",
    "SY": "Syria",
    "TZ": "Tanzania",
    "US": "United States",
    "VE": "Venezuela",
    "VN": "Vietnam",
}


def main() -> None:
    on_map = {f["properties"]["iso2"] for f in json.loads(GEOJSON.read_text())["features"]}
    entries: list[tuple[str, str]] = []
    for country in pycountry.countries:
        if country.alpha_2 not in on_map:
            continue
        name = DISPLAY_OVERRIDES.get(
            country.alpha_2, getattr(country, "common_name", None) or country.name
        )
        entries.append((country.alpha_2, name))
    if "XK" in on_map:
        entries.append(("XK", "Kosovo"))
    entries.sort(key=lambda e: e[1])

    # Pack entries into lines without ever breaking inside a string literal.
    lines: list[str] = ["    "]
    for code, name in entries:
        item = f'("{code}", "{name}"), '
        if len(lines[-1]) + len(item) > 96:
            lines.append("    ")
        lines[-1] += item
    body = "COUNTRIES: list[Country] = [\n" + "\n".join(line.rstrip() for line in lines) + "\n]\n"
    OUT.write_text(HEADER + body + FOOTER)
    print(f"Wrote {len(entries)} countries -> {OUT}")


if __name__ == "__main__":
    main()
